ov5640_camera-objs := ov5640.o
obj-$(CONFIG_MXC_CAMERA_OV5640) += ov5640_camera.o

ov5642_camera-objs := ov5642.o
obj-$(CONFIG_MXC_CAMERA_OV5642) += ov5642_camera.o

ov5640_camera_mipi-objs := ov5640_mipi.o
obj-$(CONFIG_MXC_CAMERA_OV5640_MIPI) += ov5640_camera_mipi.o

adv7180_tvin-objs := adv7180.o
obj-$(CONFIG_MXC_TVIN_ADV7180) += adv7180_tvin.o

adv7280_tvin-objs := adv7280.o
obj-$(CONFIG_MXC_TVIN_ADV7280) += adv7280_tvin.o

adv7283_tvin-objs := adv7283.o
obj-$(CONFIG_MXC_TVIN_ADV7283) += adv7283_tvin.o
